steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/label-studio-424123/label-studio', '.']
  env:
  - 'BUILDPLATFORM=linux/amd64'
  - 'NODE_VERSION=14'
images: ['gcr.io/label-studio-424123/label-studio']