info = {"message": "docs: Add release notes for 2.11.1 (#5807)", "commit": "3c1d4d92c11e660fe5a3e20d0e77cf1f1a39e2ba", "date": "2024/04/30 15:58:06", "branch": "develop", "version": "3c1d4d92+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
