# Generated by Django 3.2.25 on 2024-09-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240503_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=256, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreeableness',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='conscientiousness',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=256, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, max_length=256, verbose_name='education level'),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=256, verbose_name='ethnicity'),
        ),
        migrations.AddField(
            model_name='user',
            name='extraversion',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=256, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='income_level',
            field=models.CharField(blank=True, max_length=256, verbose_name='income level'),
        ),
        migrations.AddField(
            model_name='user',
            name='neuroticism',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='openness',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='political_affiliation',
            field=models.CharField(blank=True, max_length=256, verbose_name='political affiliation'),
        ),
        migrations.AddField(
            model_name='user',
            name='religious_affiliation',
            field=models.CharField(blank=True, max_length=256, verbose_name='religious affiliation'),
        ),
    ]
